name: Cpplint
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: Cpplint
    runs-on: ubuntu-20.04

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Install Python
      - uses: actions/setup-python@v1

      - name: Install Cpplint
        run: pip install cpplint

      - name: Run Cpplint
        run: cpplint --recursive .
